package myModel;
// Generated 2016-1-1 14:39:36 by Hibernate Tools 4.3.1.Final

import java.util.Set;

/**
 * Album generated by hbm2java
 */
public class Album implements java.io.Serializable {

	private int albumId;
	private String albumName;
	private int singerId;
	private String albumCover;
	private String albumInfo;
	private Set users;
	
	
	public Album() {
	}

	public Album(int albumId, String albumName, int singerId) {
		this.albumId = albumId;
		this.albumName = albumName;
		this.singerId = singerId;
	}

	public Album(int albumId, String albumName, int singerId, String albumCover, String albumInfo) {
		this.albumId = albumId;
		this.albumName = albumName;
		this.singerId = singerId;
		this.albumCover = albumCover;
		this.albumInfo = albumInfo;
	}

	public int getAlbumId() {
		return this.albumId;
	}

	public void setAlbumId(int albumId) {
		this.albumId = albumId;
	}

	public String getAlbumName() {
		return this.albumName;
	}

	public void setAlbumName(String albumName) {
		this.albumName = albumName;
	}

	public int getSingerId() {
		return this.singerId;
	}

	public void setSingerId(int singerId) {
		this.singerId = singerId;
	}

	public String getAlbumCover() {
		return this.albumCover;
	}

	public void setAlbumCover(String albumCover) {
		this.albumCover = albumCover;
	}

	public String getAlbumInfo() {
		return this.albumInfo;
	}

	public void setAlbumInfo(String albumInfo) {
		this.albumInfo = albumInfo;
	}
	public Set getUsers() {
		return users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

	

}
