package myModel;
// Generated 2016-1-1 14:39:36 by Hibernate Tools 4.3.1.Final

/**
 * Purchasehistory generated by hbm2java
 */
public class Purchasehistory implements java.io.Serializable {

	private PurchasehistoryId id;

	public Purchasehistory() {
	}

	public Purchasehistory(PurchasehistoryId id) {
		this.id = id;
	}

	public PurchasehistoryId getId() {
		return this.id;
	}

	public void setId(PurchasehistoryId id) {
		this.id = id;
	}

}
