package myModel;
// Generated 2016-1-1 14:39:36 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Singer generated by hbm2java
 */
public class Singer implements java.io.Serializable {

	private Integer singerId;
	private String singerName;
	private String singerInfo;
	private Set albums = new HashSet(); 
    

	
	public Singer() {
	}

	public Singer(String singerName) {
		this.singerName = singerName;
	}

	public Singer(String singerName, String singerInfo) {
		this.singerName = singerName;
		this.singerInfo = singerInfo;
	}

	public Integer getSingerId() {
		return this.singerId;
	}

	public void setSingerId(Integer singerId) {
		this.singerId = singerId;
	}

	public String getSingerName() {
		return this.singerName;
	}

	public void setSingerName(String singerName) {
		this.singerName = singerName;
	}

	public String getSingerInfo() {
		return this.singerInfo;
	}

	public void setSingerInfo(String singerInfo) {
		this.singerInfo = singerInfo;
	}

    public Set getAlbums() {
		return albums;
	}

	public void setAlbums(Set albums) {
		this.albums = albums;
	}
}
