package myModel;
// Generated 2016-1-1 14:39:36 by Hibernate Tools 4.3.1.Final

/**
 * Song generated by hbm2java
 */
public class Song implements java.io.Serializable {

	private Integer songId;
	private String songName;
	private int singerId;
	private String songUrl;
	private int albumId;
	private String lyric;

	public Song() {
	}

	public Song(String songName, int singerId, String songUrl, int albumId) {
		this.songName = songName;
		this.singerId = singerId;
		this.songUrl = songUrl;
		this.albumId = albumId;
	}

	public Song(String songName, int singerId, String songUrl, int albumId, String lyric) {
		this.songName = songName;
		this.singerId = singerId;
		this.songUrl = songUrl;
		this.albumId = albumId;
		this.lyric = lyric;
	}

	public Integer getSongId() {
		return this.songId;
	}

	public void setSongId(Integer songId) {
		this.songId = songId;
	}

	public String getSongName() {
		return this.songName;
	}

	public void setSongName(String songName) {
		this.songName = songName;
	}

	public int getSingerId() {
		return this.singerId;
	}

	public void setSingerId(int singerId) {
		this.singerId = singerId;
	}

	public String getSongUrl() {
		return this.songUrl;
	}

	public void setSongUrl(String songUrl) {
		this.songUrl = songUrl;
	}

	public int getAlbumId() {
		return this.albumId;
	}

	public void setAlbumId(int albumId) {
		this.albumId = albumId;
	}

	public String getLyric() {
		return this.lyric;
	}

	public void setLyric(String lyric) {
		this.lyric = lyric;
	}

}
