package myModel;

import java.util.Set;

import org.hibernate.type.descriptor.sql.TinyIntTypeDescriptor;

// Generated 2016-1-1 14:39:36 by Hibernate Tools 4.3.1.Final

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer userId;
	private String userName;
	private String userPwd;
	private byte isAdmin;
	private Set albums;
	
	public User() {
		
	}

	public User(String userName, String userPwd) {
		this.userName = userName;
		this.userPwd = userPwd;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserPwd() {
		return this.userPwd;
	}

	public void setUserPwd(String userPwd) {
		this.userPwd = userPwd;
	}
	public Set getAlbums() {
		return albums;
	}

	public void setAlbums(Set albums) {
		this.albums = albums;
	}
	public byte getisAdmin() {
		return isAdmin;
	}

	public void setisAdmin(byte isAdmin) {
		this.isAdmin = isAdmin;
	}
	

}
